# syntax=docker/dockerfile:1

FROM debian:bookworm-slim

LABEL maintainer="ya-k0v"
LABEL description="MMRC FFmpeg/FFprobe helper container"
LABEL version="3.3.0"

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /data

ENTRYPOINT ["sh", "-c", "exec \"$@\"", "entrypoint"]
